
print("Hello im KADY, your friendly assitant")
print("lets get to know each other")
answer = input("Whats your name? --")
print("Hi",answer)
ans = input("what is your favorite color?--")
print(ans,"is my favorite color too :)")
print("it looks like we have something common")
print("whats wrong?")
print("Oh your thirsty")
print("no worries ill get you a drink")
drink = input("what would you like to drink?--")
print("A",drink,"Coming right up")
print("WHAT!")
print("Now your hungry?!")
print("so demanding geez >:")
print("At least i get paid to be your assitant")
